version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Path to the frontend directory
    ports:
      - "3000:80"  # Nginx serving the frontend on port 80, exposed as 3000
    environment:
      - REACT_APP_API_URL=http://backend:3001  # Backend URL used by frontend
    depends_on:
      - backend  # Ensures frontend waits for the backend service

  backend:
    build:
      context: ./backend  # Path to the backend directory
    ports:
      - "3001:3001"  # Expose backend on port 3001
    environment:
      - NODE_ENV=production  # Optional: Set environment variables like NODE_ENV
