name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Set your Docker Hub username in secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Set your Docker Hub password in secrets
    
    - name: Build Docker images
      run: |
        docker build -t faaizan/frontend-app:latest ./frontend
        docker build -t faaizan/backend-app:latest ./backend
    
    - name: Log in to AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Set your AWS region

    - name: Push Docker images to Docker Hub
      run: |
        docker push faaizan/frontend-app:latest
        docker push faaizan/backend-app:latest
    
    - name: Deploy to EC2 instance
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          docker pull faaizan/frontend-app:latest
          docker pull faaizan/backend-app:latest
          docker-compose -f /path/to/your/docker-compose.yml up -d
        EOF
