name: CI/CD Workflow

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Ensure this step is used to pull the repository code

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1  # Ensure Docker is set up correctly

      - name: Build Docker image
        run: docker build -t faaizan/mywebapp .  # Building the Docker image with the name 'faaizan/mywebapp'

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Login using Docker Hub credentials stored as secrets
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # GitHub secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub secret

      - name: Push Docker image to Docker Hub
        run: docker push faaizan/mywebapp  # Push the Docker image to Docker Hub
